apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: djangofluent
      context: .
      custom:
        buildCommand: sh skaffold-builder.sh
      #docker:
      #  buildArgs:
      #    GIT_VERSION: '{{if .IMAGE_TAG}}{{.IMAGE_TAG}}{{else}}0.0.0dev0{{end}}'
  tagPolicy:
    gitCommit:
      ignoreChanges: true  # no -dirty flag
test:
  - image: djangofluent
    custom:
      - command: docker run -u root --rm $IMAGE py.test --cov --nomigrations
profiles:
  - name: dev
    manifests:
      kustomize:
        paths:
          - deployment/kustomize/environments/dev
    deploy:
      kubectl: {}
      kubeContext: docker-desktop
  - name: tst
    manifests:
      kustomize:
        paths:
          - deployment/kustomize/environments/tst
    deploy:
      kubectl: {}
      kubeContext: k3s
  - name: prd
    manifests:
      kustomize:
        paths:
          - deployment/kustomize/environments/prd
    deploy:
      kubectl: {}
      kubeContext: k3s
