#!/bin/sh
set -e

if [ -z "$1" -o -z "$2" ]; then
  echo "Usage: $0 RELEASE-NAME CHART_DIR [helm-args]" >&2
  echo "e.g.: $0 myapp /myapp/deploy/chart/ -f "values-${CI_ENVIRONMENT_SLUG:-prd}.yml" --set="image.tag=${CI_COMMIT_TAG:-1.0}",nameOverride=\$CI_ENVIRONMENT_SLUG"
  exit 1
fi

RELEASE_NAME="$1"
APP_NAME=$CI_ENVIRONMENT_SLUG
TILLER_NAMESPACE=${TILLER_NAMESPACE:-$KUBE_NAMESPACE}

# GitLab requires app=$CI_ENVIRONMENT_SLUG to monitor releases (for reviews)
# helm init --client-only is only needed when using default charts

echo "Using tiller in namespace $TILLER_NAMESPACE"
echo "Current release:"
helm ls --tiller-namespace "$TILLER_NAMESPACE" --namespace "$KUBE_NAMESPACE" $RELEASE_NAME

echo
echo "Deploying app $APP_NAME (git ${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME} $CI_COMMIT_SHA)"
set -x
helm upgrade --install --tiller-namespace "$TILLER_NAMESPACE" --namespace "$KUBE_NAMESPACE" --reset-values --set="nameOverride=$APP_NAME" "$@"
{ set +x; } 2>/dev/null

echo
echo "Follow the release status using:"
echo
echo "  helm status --tiller-namespace=$TILLER_NAMESPACE $RELEASE_NAME"
echo
