apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangofluent
spec:
  template:
    spec:
      containers:
        - name: uwsgi
          envFrom:
            - configMapRef:
                name: djangofluent-env
            - secretRef:
                name: djangofluent-env-prd # not build in kustomize

      nodeSelector:
        purpose: apps

      priorityClassName: prd-apps

      # Speed up, remove DNS dependencies
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      hostAliases:
        - hostnames: ["pgbouncer-apps.infra"]
          ip: 10.43.242.171
        - hostnames: ["postgres-apps.infra"]
          ip: 10.43.86.136
        - hostnames: ["redis-master.infra"]
          ip: 10.43.26.82

---
apiVersion: batch/v1
kind: Job
metadata:
  name: djangofluent-migrate
spec:
  template:
    spec:
      containers:
        - name: migrate
          envFrom:
            - configMapRef:
                name: djangofluent-env
            - secretRef:
                name: djangofluent-env-prd # not build in kustomize

      nodeSelector:
        purpose: apps

      priorityClassName: prd-apps

      # Speed up, remove DNS dependencies
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      hostAliases:
        - hostnames: ["pgbouncer-apps.infra"]
          ip: 10.43.242.171
        - hostnames: ["postgres-apps.infra"]
          ip: 10.43.86.136
        - hostnames: ["redis-master.infra"]
          ip: 10.43.26.82
