apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangofluent
spec:
  template:
    spec:
      containers:
        - name: uwsgi
          envFrom:
            - configMapRef:
                name: djangofluent-env
            - secretRef:
                name: djangofluent-env-prd # not build in kustomize

      nodeSelector:
        purpose: apps

      priorityClassName: prd-apps

      # Speed up, remove DNS dependencies
      hostAliases:
        - hostnames: ["pgbouncer-apps.infra"]
          ip: 10.112.2.12
        - hostnames: ["postgres-apps.infra"]
          ip: 10.112.0.102
        - hostnames: ["redis-master.infra"]
          ip: 10.112.12.219

---
apiVersion: batch/v1
kind: Job
metadata:
  name: djangofluent-migrate
spec:
  template:
    spec:
      containers:
        - name: migrate
          envFrom:
            - configMapRef:
                name: djangofluent-env
            - secretRef:
                name: djangofluent-env-prd # not build in kustomize

      nodeSelector:
        purpose: apps

      priorityClassName: prd-apps

      # Speed up, remove DNS dependencies
      hostAliases:
        - hostnames: ["pgbouncer-apps.infra"]
          ip: 10.112.2.12
        - hostnames: ["postgres-apps.infra"]
          ip: 10.112.0.102
        - hostnames: ["redis-master.infra"]
          ip: 10.112.12.219
