source "https://rubygems.org"

gem 'sass', ">= 3.4.7"
gem 'compass', "1.0.1"
gem 'bootstrap-sass', "2.3.2.2"  # not 3.x

#gem 'sass-globbing', ">= 1.1.0"

gem 'oily_png', ">= 1.1.1"  # optimize sass PNG rendering
gem 'listen', "2.7.1"
gem 'guard', ">= 2.8.1"

gem 'guard-livereload', ">= 2.1.2"
gem 'guard-compass', ">= 1.1.0"
