# A sample Guardfile
# More info at https://github.com/guard/guard#readme
#
# Installation requirements:
#
#   gem install guard-livereload guard-compass
#
# Browser plugins:
#   All: http://help.livereload.com/kb/general-use/browser-extensions
#   Firefox (2.0.9 dev release): https://github.com/siasia/livereload-extensions/downloads
#
notification :off
interactor :off
logger :level => :info

group :development do

  guard 'livereload', :host => '127.0.0.1' do
    watch(%r{.+\.(css|js|html)$})
    #watch(%r{.+\.(css|js|html|pyc)$})
  end

  if File.exists?("./config.rb")
    # Compile on start.
    puts "Compiling sass files using compass:"
    puts `compass compile --time --quiet`

    guard 'compass' do
      watch(%r{(.*)\.s[ac]ss$})
    end
  end
end
