apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: djangofluent
spec:
  rules:
    - host: django-fluent.localk8s
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: djangofluent
                port:
                  number: 80
